project_id = "qkxwyicmkuamiftimdxv"

[functions.admin-users]
verify_jwt = false

[functions.import-csv]
verify_jwt = false

[functions.import-dataset]
verify_jwt = false

[functions.import-ibge-populations]
verify_jwt = false
